language: go

go:
  - 1.8.x

install:
#  - go get github.com/vaporz/turbo-example
  - go get github.com/vaporz/turbo
  - go get github.com/kylelemons/go-gypsy/yaml
  - go get github.com/gorilla/mux
  - go get google.golang.org/grpc
  - go get git.apache.org/thrift.git/lib/go/thrift
  - go get github.com/spf13/cobra
  - go get github.com/spf13/viper
