config:
  http_port: 8081
  grpc_service_name: YourService
  grpc_service_address: 127.0.0.1:50051
  thrift_service_name: YourService
  thrift_service_address: 127.0.0.1:50052
  filter_proto_json: true
  filter_proto_json_emit_zerovalues: true
  filter_proto_json_int64_as_number: false

# TODO make a grpc plugin to generate this mapping
grpc-fieldmapping:
  - SayHelloRequest [CommonValues values]

# TODO make a thrift plugin to generate this mapping
thrift-fieldmapping:
  - CommonValues
  - HelloValues

urlmapping:
  - GET,POST /hello SayHello
  - GET /eat_apple/{num:[0-9]+} EatApple
  - GET /a/a EatApple
  - POST /a/a SayHello
  - GET /a/b EatApple
  - GET /a/c EatApple
  - GET /testproto TestProto